title: Attic Admin
description: Documenting my servers, networking, and self-hosted services. All the infrastructure apart from few vps that are currently used to access everything on my network are hosted locally.
theme: minima

# If you want to group your documentation separately from blog posts
collections:
  inventory:
    output: true
    permalink: /inventory/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  templates:
    output: true
    permalink: /templates/:path
  logs:
    output: true
    permalink: /logs/:path
